// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhfkmmkIBk3vxi4Y2Vx72u7RGBj88M0JY',
    appId: '1:301179658605:android:165542e4c4cb452d713a64',
    messagingSenderId: '301179658605',
    projectId: 'fir-98218',
    databaseURL: 'https://fir-98218-default-rtdb.firebaseio.com',
    storageBucket: 'fir-98218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ0rURcY-_6zxRwVK3KL6HLjmFxK8yzTk',
    appId: '1:301179658605:ios:fb66c589201dc3cc713a64',
    messagingSenderId: '301179658605',
    projectId: 'fir-98218',
    databaseURL: 'https://fir-98218-default-rtdb.firebaseio.com',
    storageBucket: 'fir-98218.appspot.com',
    iosClientId: '301179658605-k0eq38glo0omn7bp2fdl282n5bp8r9r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
